name: CI — Tests & Cluster Mints Validation

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  test-and-validate:
    name: Run tests and validate cluster mints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: backend

      - name: Run backend tests
        run: npm test --silent
        working-directory: backend

      - name: Validate cluster mints
        run: npm run validate:cluster-mints
        working-directory: backend
