name: Integration - simulate-confirm

on:
  push:
    branches:
      - feature/simulate-integration-final
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/integration-simulate.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/integration-simulate.yml'

jobs:
  run-emulator-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install firebase-tools
        run: |
          npm install -g firebase-tools@11

      - name: Print firebase-tools version
        run: |
          echo "firebase-tools: $(firebase --version)"

      - name: Setup Java (required by some emulators)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Validate required secrets (fallback allowed)
        shell: bash
        env:
          DEV_SIMULATE_KEY: ${{ secrets.DEV_SIMULATE_KEY }}
          DEV_CLEANUP_KEY: ${{ secrets.DEV_CLEANUP_KEY }}
        run: |
          # Use GitHub secrets if available; otherwise expose safe fallbacks so forks/CI can run.
          if [ -n "$DEV_SIMULATE_KEY" ] && [ -n "$DEV_CLEANUP_KEY" ]; then
            echo "Using provided secrets for DEV_SIMULATE_KEY and DEV_CLEANUP_KEY";
            echo "DEV_SIMULATE_KEY=$DEV_SIMULATE_KEY" >> $GITHUB_ENV;
            echo "DEV_CLEANUP_KEY=$DEV_CLEANUP_KEY" >> $GITHUB_ENV;
          else
            echo "WARNING: DEV_SIMULATE_KEY or DEV_CLEANUP_KEY not set. Writing fallback test keys to GITHUB_ENV.";
            echo "DEV_SIMULATE_KEY=dev-local-key" >> $GITHUB_ENV;
            echo "DEV_CLEANUP_KEY=dev-local-cleanup" >> $GITHUB_ENV;
          fi

      - name: Patch backend package.json engines for emulator
        working-directory: .
        run: |
          echo "Patching backend/package.json engines.node -> 18 for Functions emulator";
          node -e "const fs=require('fs');const p='backend/package.json';if(!fs.existsSync(p)){console.error('backend/package.json not found');process.exit(0);}const j=JSON.parse(fs.readFileSync(p));j.engines=j.engines||{};j.engines.node='18';fs.writeFileSync(p,JSON.stringify(j,null,2));console.log('patched');"

      - name: Install backend deps
        working-directory: backend
        run: |
          npm ci

      - name: Build backend
        working-directory: backend
        run: |
          echo "Building backend (TypeScript -> dist)";
          npm run build

      - name: Show built backend files (debug)
        run: |
          echo "Listing backend/dist";
          ls -la backend/dist || true;
          echo "--- head of backend/dist/index.js ---";
          if [ -f backend/dist/index.js ]; then head -n 120 backend/dist/index.js || true; else echo "backend/dist/index.js not found"; fi

      - name: Show patched backend/package.json (debug)
        run: |
          echo "--- backend/package.json after CI patch ---";
          cat backend/package.json || true;

      - name: Run integration simulate test under emulators (debug)
        working-directory: backend
        env:
          FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
          NODE_ENV: development
        run: |
          # Use emulators:exec --debug to capture emulator internals. DEV keys are provided via $GITHUB_ENV.
          echo "Using DEV_SIMULATE_KEY=$(printenv DEV_SIMULATE_KEY)";
          echo "Node version: $(node -v)";
          firebase emulators:exec --project=metartpay-bac2f --debug "node tools/integration_simulate_test.js"
