name: Integration - simulate-confirm

on:
  push:
    branches:
      - feature/simulate-integration-final
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/integration-simulate.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/integration-simulate.yml'

jobs:
  run-emulator-and-tests:
  runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install firebase-tools
        run: |
          npm install -g firebase-tools@11

      - name: Install backend deps
        working-directory: backend
        run: |
          npm ci

      - name: Start emulators (Functions + Firestore)
        run: |
          # Start emulators in background
          firebase emulators:start --only functions,firestore --project=metartpay-bac2f &
          # Poll Functions emulator root endpoint until ready (up to 60s)
          SECONDS=0
          until curl -sSf "http://127.0.0.1:5001/" >/dev/null 2>&1 || [ $SECONDS -ge 60 ]; do
            sleep 2
            SECONDS=$((SECONDS + 2))
            echo "Waiting for Functions emulator... ${SECONDS}s"
          done
          if [ $SECONDS -ge 60 ]; then
            echo "Functions emulator did not become ready after 60s" >&2
            exit 1
          fi

      - name: Run integration simulate test
        env:
          FIRESTORE_EMULATOR_HOST: 127.0.0.1:8080
          DEV_SIMULATE_KEY: ${{ secrets.DEV_SIMULATE_KEY }}
          DEV_CLEANUP_KEY: ${{ secrets.DEV_CLEANUP_KEY }}
          NODE_ENV: development
        working-directory: backend
        run: |
          node tools/integration_simulate_test.js

      - name: Stop emulators
        run: |
          # Kill firebase emulator background process
          pkill -f "firebase" || true
